export const sampleData = [
    { id: 0, parent: null, name: 'ROOT' },
    { id:1, parentId: 0, name: 'Sergent Bruineman', title: 'CEO', avatar: 'https://robohash.org/fugitadmollitia.png?size=100x100&set=set1' },
    { id:2, parentId: 1, name: 'Maurie Punt', title: 'Occupational Therapist', avatar: 'https://robohash.org/vitaeperferendisvoluptas.png?size=100x100&set=set1' },
    { id:3, parentId: 1, name: 'Brandyn Regelous', title: 'Librarian', avatar: 'https://robohash.org/fugaeumplaceat.png?size=100x100&set=set1' },
    { id:4, parentId: 1, name: 'Denney Greenside', title: 'Research Associate', avatar: 'https://robohash.org/veldolorumincidunt.png?size=100x100&set=set1' },
    { id:5, parentId: 1, name: 'Laurena Dore', title: 'Editor', avatar: 'https://robohash.org/delenitieosratione.png?size=100x100&set=set1' },
    { id:6, parentId: 2, name: 'Marget Bunten', title: 'VP Product Management', avatar: 'https://robohash.org/temporaautsunt.png?size=100x100&set=set1' },
    { id:7, parentId: 2, name: 'Myrah Nadin', title: 'Sales Associate', avatar: 'https://robohash.org/voluptatemessequos.png?size=100x100&set=set1' },
    { id:8, parentId: 2, name: 'Karisa St Leger', title: 'Director of Sales', avatar: 'https://robohash.org/nonexdeleniti.png?size=100x100&set=set1' },
    { id:9, parentId: 3, name: 'Isadora Kibblewhite', title: 'Human Resources Assistant I', avatar: 'https://robohash.org/eosdoloresvel.png?size=100x100&set=set1' },
    { id:10, parentId: 3, name: 'Sella Jorin', title: 'Administrative Officer', avatar: 'https://robohash.org/praesentiumrerumdolore.png?size=100x100&set=set1' },
    { id:11, parentId: 3, name: 'Dorolisa Asker', title: 'Help Desk Technician', avatar: 'https://robohash.org/laudantiumsitfugit.png?size=100x100&set=set1' },
    { id:12, parentId: 4, name: 'Sharona Segrave', title: 'Community Outreach Specialist', avatar: 'https://robohash.org/quaeratautfugit.png?size=100x100&set=set1' },
    { id:13, parentId: 4, name: 'Germaine Swiggs', title: 'Sales Associate', avatar: 'https://robohash.org/asperioreseaqueaut.png?size=100x100&set=set1' },
    { id:14, parentId: 5, name: 'Yalonda Dellit', title: 'Professor', avatar: 'https://robohash.org/molestiaenemoet.png?size=100x100&set=set1' },
    { id:15, parentId: 5, name: 'Maire Gouge', title: 'Graphic Designer', avatar: 'https://robohash.org/eumtemporibusblanditiis.png?size=100x100&set=set1' },
    { id:16, parentId: 6, name: 'Waldemar Gumery', title: 'Financial Advisor', avatar: 'https://robohash.org/suntnatusatque.png?size=100x100&set=set1' },
    { id:17, parentId: 7, name: 'Prinz Rowsel', title: 'Analog Circuit Design manager', avatar: 'https://robohash.org/blanditiisquonihil.png?size=100x100&set=set1' },
    { id:18, parentId: 7, name: 'Thaxter Winchcum', title: 'Web Designer IV', avatar: 'https://robohash.org/sitnonenim.png?size=100x100&set=set1' },
    { id:19, parentId: 7, name: 'Keven Hysom', title: 'VP Sales', avatar: 'https://robohash.org/oditpariaturnihil.png?size=100x100&set=set1' },
    { id:20, parentId: 7, name: 'Cally Rimbault', title: 'Administrative Assistant I', avatar: 'https://robohash.org/pariaturnemoodio.png?size=100x100&set=set1' },
    { id:21, parentId: 8, name: 'Marina Riby', title: 'Budget/Accounting Analyst IV', avatar: 'https://robohash.org/quaenullaaut.png?size=100x100&set=set1' },
    { id:22, parentId: 9, name: 'Wynn Glander', title: 'Electrical Engineer', avatar: 'https://robohash.org/quianullaillum.png?size=100x100&set=set1' },
    { id:23, parentId: 9, name: 'Alistair Gittings', title: 'Office Assistant II', avatar: 'https://robohash.org/doloristedolores.png?size=100x100&set=set1' },
    { id:24, parentId: 9, name: 'Alvy Crawshaw', title: 'Recruiting Manager', avatar: 'https://robohash.org/nullatemporaquia.png?size=100x100&set=set1' },
    { id:25, parentId: 9, name: 'Roze Skep', title: 'Programmer II', avatar: 'https://robohash.org/asperioresdolorescumque.png?size=100x100&set=set1' },
    { id:26, parentId: 10, name: 'Lesli Riall', title: 'Product Engineer', avatar: 'https://robohash.org/aperiamquiquisquam.png?size=100x100&set=set1' },
    { id:27, parentId: 10, name: 'Bordie Kimmel', title: 'Assistant Media Planner', avatar: 'https://robohash.org/odioineveniet.png?size=100x100&set=set1' },
    { id:28, parentId: 11, name: 'Elia Ralestone', title: 'Software Engineer II', avatar: 'https://robohash.org/enimaliasanimi.png?size=100x100&set=set1' },
    { id:29, parentId: 12, name: 'Gawen Pellissier', title: 'Programmer Analyst III', avatar: 'https://robohash.org/dolorumadet.png?size=100x100&set=set1' },
    { id:30, parentId: 12, name: 'Alvan Colrein', title: 'Account Executive', avatar: 'https://robohash.org/officiadolorumsint.png?size=100x100&set=set1' },
    { id:31, parentId: 13, name: 'Valli Varfolomeev', title: 'Database Administrator I', avatar: 'https://robohash.org/quaeratmagnieos.png?size=100x100&set=set1' },
    { id:32, parentId: 14, name: 'Dwayne Keoghane', title: 'Payment Adjustment Coordinator', avatar: 'https://robohash.org/quosquoddeserunt.png?size=100x100&set=set1' },
    { id:33, parentId: 15, name: 'Merrill Pearcehouse', title: 'Cost Accountant', avatar: 'https://robohash.org/aliquamearumadipisci.png?size=100x100&set=set1' },
    { id:34, parentId: 15, name: 'Sula De Angelo', title: 'Analyst Programmer', avatar: 'https://robohash.org/suntquoanimi.png?size=100x100&set=set1' },
    { id:35, parentId: 15, name: 'Lannie Cecchetelli', title: 'Junior Executive', avatar: 'https://robohash.org/quiautvoluptatibus.png?size=100x100&set=set1' },
    { id:36, parentId: 16, name: 'Mandel Buckenham', title: 'Food Chemist', avatar: 'https://robohash.org/utrationeesse.png?size=100x100&set=set1' },
    { id:37, parentId: 16, name: 'Henriette Bristow', title: 'Recruiter', avatar: 'https://robohash.org/vitaeutmaiores.png?size=100x100&set=set1' },
    { id:38, parentId: 16, name: 'Jermain ducarme', title: 'General Manager', avatar: 'https://robohash.org/autveniamquae.png?size=100x100&set=set1' },
    { id:39, parentId: 16, name: 'Griswold Fabbri', title: 'General Manager', avatar: 'https://robohash.org/ullamdistinctiodolore.png?size=100x100&set=set1' },
    { id:40, parentId: 16, name: 'Joice Gemnett', title: 'Engineer II', avatar: 'https://robohash.org/etsolutadeleniti.png?size=100x100&set=set1' },
    { id:41, parentId: 17, name: 'Staford Orton', title: 'Data Coordiator', avatar: 'https://robohash.org/reprehenderitliberoquis.png?size=100x100&set=set1' },
    { id:42, parentId: 18, name: 'Shanda Simchenko', title: 'Financial Analyst', avatar: 'https://robohash.org/quisquamaspernaturet.png?size=100x100&set=set1' },
    { id:43, parentId: 18, name: 'Pearla Jiricka', title: 'Help Desk Operator', avatar: 'https://robohash.org/eosipsamvel.png?size=100x100&set=set1' },
    { id:44, parentId: 19, name: 'Ophelia Moulsdall', title: 'Programmer Analyst III', avatar: 'https://robohash.org/officiareprehenderitdicta.png?size=100x100&set=set1' },
    { id:45, parentId: 19, name: 'Jarrett Cumberlidge', title: 'Systems Administrator III', avatar: 'https://robohash.org/omnisnullaquidem.png?size=100x100&set=set1' },
    { id:46, parentId: 20, name: 'Enoch Abrahart', title: 'Structural Engineer', avatar: 'https://robohash.org/voluptateipsameveniet.png?size=100x100&set=set1' },
    { id:47, parentId: 21, name: 'Josey Ellingham', title: 'Environmental Tech', avatar: 'https://robohash.org/aliasrepudiandaesimilique.png?size=100x100&set=set1' },
    { id:48, parentId: 23, name: 'Kimberley Adan', title: 'Chemical Engineer', avatar: 'https://robohash.org/asperioresestvoluptatibus.png?size=100x100&set=set1' },
    { id:49, parentId: 24, name: 'Cornell Hilary', title: 'General Manager', avatar: 'https://robohash.org/evenietdoloremipsa.png?size=100x100&set=set1' },
    { id:50, parentId: 25, name: 'Charissa Doak', title: 'Design Engineer', avatar: 'https://robohash.org/repudiandaenemonihil.png?size=100x100&set=set1' },
    { id:51, parentId: 26, name: 'Clemence Elward', title: 'Programmer III', avatar: 'https://robohash.org/rerumauteos.png?size=100x100&set=set1' },
    { id:52, parentId: 27, name: 'Darsey Lawler', title: 'Office Assistant II', avatar: 'https://robohash.org/estessequis.png?size=100x100&set=set1' },
    { id:53, parentId: 27, name: 'Oran Fouracre', title: 'Systems Administrator I', avatar: 'https://robohash.org/rerumidveritatis.png?size=100x100&set=set1' },
    { id:54, parentId: 27, name: 'Fernande Berggren', title: 'Nuclear Power Engineer', avatar: 'https://robohash.org/repudiandaemaioresat.png?size=100x100&set=set1' },
    { id:55, parentId: 28, name: 'Bran Romans', title: 'Actuary', avatar: 'https://robohash.org/repellendusmollitiaenim.png?size=100x100&set=set1' },
    { id:56, parentId: 29, name: 'Rena Nitto', title: 'Administrative Officer', avatar: 'https://robohash.org/doloribusplaceatqui.png?size=100x100&set=set1' },
    { id:57, parentId: 30, name: 'Philip Repp', title: 'Senior Editor', avatar: 'https://robohash.org/odiocumnon.png?size=100x100&set=set1' },
    { id:58, parentId: 30, name: 'Allsun Matterface', title: 'Office Assistant II', avatar: 'https://robohash.org/illumcupiditatesint.png?size=100x100&set=set1' },
    { id:59, parentId: 31, name: 'Arluene Eustis', title: 'Senior Cost Accountant', avatar: 'https://robohash.org/idevenietconsequatur.png?size=100x100&set=set1' },
    { id:60, parentId: 49, name: 'Bari Sainsbury-Brown', title: 'Marketing Assistant', avatar: 'https://robohash.org/eaquaeratvoluptatibus.png?size=100x100&set=set1' },
    { id:61, parentId: 49, name: 'Leelah Hadley', title: 'Structural Analysis Engineer', avatar: 'https://robohash.org/quoassumendavoluptatum.png?size=100x100&set=set1' },
    { id:62, parentId: 49, name: 'Alisha Maplethorpe', title: 'Safety Technician III', avatar: 'https://robohash.org/optiovoluptatemeos.png?size=100x100&set=set1' },
    { id:63, parentId: 49, name: 'Mel Nasey', title: 'Junior Executive', avatar: 'https://robohash.org/aliquamadipisciid.png?size=100x100&set=set1' },
    { id:64, parentId: 49, name: 'Averil Dollard', title: 'Graphic Designer', avatar: 'https://robohash.org/voluptatibusrerumvelit.png?size=100x100&set=set1' },
    { id:65, parentId: 49, name: 'Chev Goulding', title: 'Software Consultant', avatar: 'https://robohash.org/fugacumlaudantium.png?size=100x100&set=set1' }
];
